version: "3.7"

services:
  db:
    image: postgis/postgis
    container_name: sonic-db
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sonic-server
    restart: always
    env_file: .env
    ports:
    - 8080:8080
    depends_on:
      - db
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
